In [ ]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

In [52]:
data_yelp = pd.read_csv('/content/yelp_labelled.txt', sep ='\t', header=None)
data_yelp.head()

0  1
0                           Wow... Loved this place.  1
1                                 Crust is not good.  0
2          Not tasty and the texture was just nasty.  0
3  Stopped by during the late May bank holiday of...  1
4  The selection on the menu was great and so wer...  1

In [ ]:
columan_name = ['Review', 'Sentiment']
data_yelp.columns = columan_name

In [ ]:
data_yelp.head()

Review  Sentiment
0                           Wow... Loved this place.          1
1                                 Crust is not good.          0
2          Not tasty and the texture was just nasty.          0
3  Stopped by during the late May bank holiday of...          1
4  The selection on the menu was great and so wer...          1

In [ ]:
data_yelp.shape

(1000, 2)

In [ ]:
data_amazon = pd.read_csv('/content/amazon_cells_labelled.txt', sep='\t', header= None)
data_amazon.head()

0  1
0  So there is no way for me to plug it in here i...  0
1                        Good case, Excellent value.  1
2                             Great for the jawbone.  1
3  Tied to charger for conversations lasting more...  0
4                                  The mic is great.  1

In [ ]:
data_amazon.columns = columan_name

In [ ]:
data_amazon.head()

Review  Sentiment
0  So there is no way for me to plug it in here i...          0
1                        Good case, Excellent value.          1
2                             Great for the jawbone.          1
3  Tied to charger for conversations lasting more...          0
4                                  The mic is great.          1

In [ ]:
data_amazon.shape

(1000, 2)

In [ ]:
data_imdb = pd.read_csv('/content/imdb_labelled.txt',sep='\t',header=None)
data_imdb.head()

0  1
0  A very, very, very slow-moving, aimless movie ...  0
1  Not sure who was more lost - the flat characte...  0
2  Attempting artiness with black & white and cle...  0
3       Very little music or anything to speak of.    0
4  The best scene in the movie was when Gerardo i...  1

In [ ]:
data_imdb.columns= columan_name

In [ ]:
data_imdb.shape

(748, 2)

In [ ]:
data= data_yelp.append([data_amazon, data_imdb],ignore_index=True)
data.shape

<ipython-input-15-a29dc45654cb>:1: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  data= data_yelp.append([data_amazon, data_imdb],ignore_index=True)


(2748, 2)

In [ ]:
data['Sentiment'].value_counts()

1    1386
0    1362
Name: Sentiment, dtype: int64

In [ ]:
data.isnull().sum()

Review       0
Sentiment    0
dtype: int64

In [ ]:
x=data['Review']
y=data['Sentiment']


Data Cleaning

In [ ]:
import string

In [ ]:
punct = string.punctuation
punct

'!"#$%&\'()*+,-./:;<=>?@[\\]^_`{|}~'

In [ ]:
!pip install spacy

In [ ]:
!pip install spacy.lang.en.stop_word

ERROR: Could not find a version that satisfies the requirement spacy.lang.en.stop_word (from versions: none)
ERROR: No matching distribution found for spacy.lang.en.stop_word


In [ ]:
from spacy.lang.en import STOP_WORDS

In [ ]:
stopwords = list(STOP_WORDS)
stopwords

['am',
 'with',
 'very',
 'really',
 'what',
 'it',
 'indeed',
 'almost',
 'until',
 'even',
 'fifteen',
 'who',
 'between',
 'cannot',
 'themselves',
 'he',
 'first',
 'against',
 'these',
 'been',
 'her',
 'whether',
 'nobody',
 'please',
 'must',
 'perhaps',
 'anything',
 '‘re',
 'else',
 'anyway',
 'back',
 'than',
 'herself',
 'you',
 'them',
 'down',
 'latterly',
 'rather',
 'yet',
 'should',
 'put',
 'via',
 'the',
 'us',
 'doing',
 'neither',
 'had',
 'few',
 'forty',
 'wherein',
 'whoever',
 'next',
 'top',
 'none',
 'after',
 'upon',
 'give',
 'sometime',
 'unless',
 'hereupon',
 'across',
 'thence',
 'whatever',
 'seeming',
 'third',
 'take',
 'no',
 'other',
 'whereby',
 'whereupon',
 'around',
 'his',
 "'re",
 'from',
 'whither',
 'whole',
 'nine',
 'those',
 'every',
 'made',
 'either',
 'may',
 'ever',
 'for',
 'therein',
 'yourself',
 'among',
 'another',
 'again',
 'wherever',
 'will',
 '’s',
 'many',
 'something',
 'towards',
 'before',
 'up',
 "'m",
 'its',
 'own',
 

In [ ]:
import spacy
nlp = spacy.load('en_core_web_sm')
def text_data_cleaning(sentence):
  doc = nlp(sentence)
  tokens = []
  for token in doc:
    if token.lemma_ != "-PRON-":
      temp = token.lemma_.lower().strip()
    else:
      temp = token.lower_
    tokens.append(temp)
  cleaned_tokens=[]
  for token in tokens:
    if token not in stopwords and token not in punct:
      cleaned_tokens.append(token)
  return cleaned_tokens


In [ ]:
text_data_cleaning("Hello all, It's a beautiful day outside there!")

['hello', 'beautiful', 'day', 'outside']

TF-IDF

In [ ]:
from sklearn.svm import LinearSVC
from sklearn.feature_extraction.text import TfidfVectorizer
from sklearn.pipeline import Pipeline


In [ ]:
tfidf = TfidfVectorizer(tokenizer= text_data_cleaning)

In [ ]:
classifier = LinearSVC()

In [ ]:
from sklearn.model_selection import train_test_split
x_train, x_test, y_train, y_test = train_test_split(x,y,test_size = 0.2, random_state= 0)

In [ ]:
x_train.shape, x_test.shape

((2198,), (550,))

In [ ]:
x_train.head()

2572    An Italian reviewer called this "a small, grea...
526                          And it was way to expensive.
1509    As an earlier review noted, plug in this charg...
144     Nice blanket of moz over top but i feel like t...
2483    The film gives meaning to the phrase, "Never i...
Name: Review, dtype: object

In [ ]:
clf = Pipeline([('tfidf', tfidf),('clf',classifier)])

In [ ]:
clf.fit(x_train,y_train)

/usr/local/lib/python3.10/dist-packages/sklearn/feature_extraction/text.py:528: UserWarning: The parameter 'token_pattern' will not be used since 'tokenizer' is not None'
  warnings.warn(


Pipeline(steps=[('tfidf',
                 TfidfVectorizer(tokenizer=<function text_data_cleaning at 0x796afb3d5870>)),
                ('clf', LinearSVC())])

In [ ]:
from sklearn.metrics import accuracy_score, classification_report, confusion_matrix

In [ ]:
y_pred = clf.predict(x_test)

In [ ]:
confusion_matrix(y_test, y_pred)

array([[201,  78],
       [ 50, 221]])

In [ ]:
print(classification_report(y_test, y_pred))

              precision    recall  f1-score   support

           0       0.80      0.72      0.76       279
           1       0.74      0.82      0.78       271

    accuracy                           0.77       550
   macro avg       0.77      0.77      0.77       550
weighted avg       0.77      0.77      0.77       550



In [ ]:
accuracy_score(y_test,y_pred)

0.7672727272727272

In [ ]:
clf.predict(["Wow, I am learning NLP in fun Fashion!"])

array([1])

In [ ]:
clf.predict(["It's hard to learn new things!"])

array([0])

In [53]:
user_input = input('Enter the review to classify\n')
clf.predict([user_input])

Enter the review to classify
 i like NLP


array([1])